spring:
  application:
    name: actionarybe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/actionary_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true  # JPA 이후 data.sql 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  jwt:
    secret: "my-super-long-secret-key"
    access-token-expiration-ms: 3600000  # 1시간

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        base-url: https://${S3_BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com
      region:
        static: ap-northeast-2
        auto: false
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      stack:
        auto: false

