spring:
  application:
    name: actionarybe
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/actionary_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6377
      timeout: 2000

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true  # JPA 이후 data.sql 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  jwt:
    secret: "my-super-long-secret-key"
    access-token-expiration-ms: 3600000  # 1시간

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        base-url: https://${S3_BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com
      region:
        static: ap-northeast-2
        auto: false
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      stack:
        auto: false

janus:
  base-url: http://localhost:8088/janus

app:
  default:
    cover-image: "https://${S3_BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com/static/default_cover/default_cover.png"

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  model: gpt-5-mini
